import { env } from "cloudflare:workers";
import type{Entity}from"./ops-core";
export function runtime():any{return env;}
export function infrastructureSummary(){const e=runtime();return{githubUrl:e.BD_GITHUB_URL||"",vercelUrl:e.BD_VERCEL_URL||"",vercelMode:e.BD_VERCEL_MODE||"",apolloChatVerified:e.BD_APOLLO_CHAT_VERIFIED==="true",apolloChatStatus:e.BD_APOLLO_CHAT_STATUS||"",ghlSignInStatus:e.BD_GHL_SIGNIN_STATUS||"",ollamaSignInStatus:e.BD_OLLAMA_SIGNIN_STATUS||"",hermesStatus:e.BD_HERMES_STATUS||"not_installed",platformCheckedAt:e.BD_PLATFORM_CHECKED_AT||""};}
export function db():D1Database{const binding=runtime().DB;if(!binding)throw new Error("El almacenamiento no está disponible. Intenta nuevamente.");return binding;}
export async function allRecords(demo:boolean):Promise<Entity[]>{const result=await db().prepare("SELECT * FROM records WHERE demo = ? ORDER BY created_at DESC").bind(demo?1:0).all<any>();return result.results.map(r=>({id:r.id,kind:r.kind,demo:!!r.demo,data:JSON.parse(r.data),version:r.version,createdAt:r.created_at,updatedAt:r.updated_at}));}
export async function getRecord(id:string,demo:boolean){const r=await db().prepare("SELECT * FROM records WHERE id = ? AND demo = ?").bind(id,demo?1:0).first<any>();if(!r)throw new Error("No se encontró el registro.");return{id:r.id,kind:r.kind,demo:!!r.demo,data:JSON.parse(r.data),version:r.version,createdAt:r.created_at,updatedAt:r.updated_at}as Entity;}
export function insertRecord(r:Entity){return db().prepare("INSERT INTO records (id,kind,demo,data,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(r.id,r.kind,r.demo?1:0,JSON.stringify(r.data),r.version,r.createdAt,r.updatedAt);}
const updateGuards=new WeakMap<object,{id:string;version:number;demo:number}>();
export function updateRecord(r:Entity,expectedVersion:number){const stmt=db().prepare("UPDATE records SET data = ?, version = version + 1, updated_at = ? WHERE id = ? AND demo = ? AND version = ?").bind(JSON.stringify(r.data),new Date().toISOString(),r.id,r.demo?1:0,expectedVersion);updateGuards.set(stmt,{id:r.id,version:expectedVersion,demo:r.demo?1:0});return stmt;}
export function fresh(kind:string,data:any,demo:boolean,id:string=crypto.randomUUID()):Entity{const now=new Date().toISOString();return{id,kind,demo,data,version:1,createdAt:now,updatedAt:now};}
export async function commit(statements:D1PreparedStatement[],requestId:string,action:string,actor:string,demo:boolean,ref=""){
 const exists=await db().prepare("SELECT id FROM audit WHERE id = ?").bind(requestId).first();if(exists)return{duplicate:true};
 const guards=statements.map(s=>updateGuards.get(s)).filter(Boolean) as {id:string;version:number;demo:number}[];
 const condition=guards.length?guards.map(()=>"EXISTS (SELECT 1 FROM records WHERE id=? AND version=? AND demo=?)").join(" AND "):"1";
 const values:any[]=guards.flatMap(g=>[g.id,g.version,g.demo]);
 const audit=db().prepare(`INSERT INTO audit (id,demo,action,actor,ref,created_at) VALUES (CASE WHEN ${condition} THEN ? ELSE NULL END,?,?,?,?,?)`).bind(...values,requestId,demo?1:0,action,actor,ref,new Date().toISOString());
 try{const results=await db().batch([audit,...statements]);return{duplicate:false,results};}catch(e:any){if(/UNIQUE constraint failed: audit.id/.test(e.message))return{duplicate:true};if(/NOT NULL constraint failed: audit.id/.test(e.message))throw new Error("El registro cambió en otra sesión. Actualiza antes de guardar.");throw e;}
}
export async function recentAudit(demo:boolean){return(await db().prepare("SELECT action,actor,ref,created_at FROM audit WHERE demo = ? ORDER BY created_at DESC LIMIT 25").bind(demo?1:0).all()).results;}
export async function seal(value:any){const master=runtime().BD_CREDENTIAL_KEY;if(!master)throw new Error("Falta activar el resguardo de credenciales.");const raw=Uint8Array.from(atob(master),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey("raw",raw,"AES-GCM",false,["encrypt"]);const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(JSON.stringify(value)));return JSON.stringify({iv:btoa(String.fromCharCode(...iv)),cipher:btoa(String.fromCharCode(...new Uint8Array(cipher)))});}
export async function credential(provider:string):Promise<any>{const row=await db().prepare("SELECT encrypted FROM credentials WHERE provider = ?").bind(provider).first<any>();if(!row)throw new Error(`Conecta ${provider} en Conexiones.`);const master=runtime().BD_CREDENTIAL_KEY;const key=await crypto.subtle.importKey("raw",Uint8Array.from(atob(master),c=>c.charCodeAt(0)),"AES-GCM",false,["decrypt"]);const payload=JSON.parse(row.encrypted);const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:Uint8Array.from(atob(payload.iv),c=>c.charCodeAt(0))},key,Uint8Array.from(atob(payload.cipher),c=>c.charCodeAt(0)));return JSON.parse(new TextDecoder().decode(plain));}
export async function connectionSummary(){return(await db().prepare("SELECT provider,status,checked_at FROM credentials").all()).results;}
