import{z}from"zod";import{allRecords,commit,connectionSummary,db,fresh,getRecord,insertRecord,recentAudit,updateRecord,runtime}from"@/lib/ops-db";import{contactSchema,estimateSchema,estimateMath,ledgerSchema,taskSchema,changeSchema,activationErrors,contactKey,addDays,sameContact,contactKeys,dateSchema}from"@/lib/ops-core";
export const dynamic="force-dynamic";
function json(data:any,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store"}});}
export async function GET(request:Request){try{const demo=new URL(request.url).searchParams.get("demo")==="1";return json({records:await allRecords(demo),audit:await recentAudit(demo),connections:await connectionSummary(),infrastructure:{githubUrl:runtime().BD_GITHUB_URL||"",vercelUrl:runtime().BD_VERCEL_URL||"",apolloChatVerified:runtime().BD_APOLLO_CHAT_VERIFIED==="true"}});}catch(e:any){return json({error:e.message},503);}}
export async function POST(request:Request){try{
 const origin=request.headers.get("origin");if(origin&&new URL(request.url).origin!==origin)throw new Error("Origen no permitido.");
 const b:any=await request.json();const requestId=z.string().uuid().parse(b.requestId),demo=b.demo===true,data=b.data||{},records=await allRecords(demo),statements:D1PreparedStatement[]=[];let ref="",notice="Guardado.";
 if(await db().prepare("SELECT id FROM audit WHERE id = ?").bind(requestId).first())return json({ok:true,duplicate:true});
 const lookup=async(id:string,kind:string)=>{const r=await getRecord(id,demo);if(r.kind!==kind)throw new Error("Tipo de registro incorrecto.");return r;};
 if(b.action==="contact"){
 const c=contactSchema.parse(data);if(c.stage==="won")throw new Error("Registra la aceptación de una cotización para ganar esta oportunidad.");const key=contactKey(c),duplicate=records.find(r=>r.kind==="contact"&&sameContact(r.data,c));if(duplicate)return json({ok:true,duplicate:true,id:duplicate.id,notice:"Ese contacto ya existe; se conservó su información."});
 const r=fresh("contact",c,demo);ref=r.id;statements.push(insertRecord(r),insertRecord(fresh("task",{title:`Contactar a ${c.name}`,owner:c.owner,due:c.nextDue,contactId:r.id,projectId:"",notes:"Calificar alcance, ubicación, fecha y presupuesto.",done:false},demo)));
 }else if(b.action==="contact-update"){
 const r=await lookup(data.id,"contact"),c=contactSchema.parse({...r.data,...data});if(c.stage==="won"&&r.data.stage!=="won")throw new Error("Registra la aceptación de una cotización para ganar esta oportunidad.");const key=contactKey(c);if(records.some(x=>x.kind==="contact"&&x.id!==r.id&&sameContact(x.data,c)))throw new Error("Ese email o teléfono pertenece a otro contacto.");r.data=c;if(data.version!==r.version)throw new Error("El contacto cambió. Actualiza la página antes de guardar.");ref=r.id;statements.push(updateRecord(r,r.version));
 }else if(b.action==="estimate"){
 const c=estimateSchema.parse(data),contact=await lookup(c.contactId,"contact"),math=estimateMath(c);if(math.costCents<=0)throw new Error("Agrega al menos un costo real a la cotización.");const r=fresh("estimate",{...c,...math,status:"draft"},demo);ref=r.id;statements.push(insertRecord(r));if(!["won","lost"].includes(contact.data.stage)){contact.data.stage="quoted";statements.push(updateRecord(contact,contact.version));}statements.push(insertRecord(fresh("task",{title:`Dar seguimiento: ${c.title}`,owner:c.owner,due:addDays(2),contactId:c.contactId,projectId:"",notes:"Revisar la cotización con el cliente.",done:false},demo)));
 }else if(b.action==="estimate-sent"){
 const r=await lookup(data.id,"estimate");if(r.data.status==="accepted")throw new Error("La cotización ya está aceptada.");r.data.status="sent";r.data.sentRef=z.string().trim().min(1).max(180).parse(data.reference);statements.push(updateRecord(r,r.version));ref=r.id;
 }else if(b.action==="accept-estimate"){
 const r=await lookup(data.id,"estimate");if(r.data.status==="accepted")return json({ok:true,duplicate:true,notice:"La obra ya fue creada."});const acceptedBy=z.string().trim().min(1).max(180).parse(data.acceptedBy),signedRef=z.string().trim().min(1).max(180).parse(data.signedRef);r.data={...r.data,status:"accepted",acceptedBy,signedRef,acceptedAt:new Date().toISOString()};
 const project=fresh("project",{estimateId:r.id,contactId:r.data.contactId,title:r.data.title,scope:r.data.scope,priceCents:r.data.priceCents,costCents:r.data.costCents,depositPct:r.data.depositPct,owner:r.data.owner,status:"scheduled",startDate:addDays(7),checks:{scope:true,quotes:false,permits:false,crew:false}},demo,`project-${r.id}`),contact=await lookup(r.data.contactId,"contact");contact.data.stage="won";ref=project.id;statements.push(updateRecord(r,r.version),insertRecord(project),updateRecord(contact,contact.version),insertRecord(fresh("task",{title:`Confirmar anticipo y preparación: ${r.data.title}`,owner:r.data.owner,due:addDays(1),projectId:project.id,contactId:r.data.contactId,notes:"Verificar contrato, anticipo, proveedores, diseño/permisos y cuadrilla.",done:false},demo)));notice="Aceptación registrada y obra creada.";
 }else if(b.action==="project-update"){
 const r=await lookup(data.id,"project");if(data.version!==r.version)throw new Error("La obra cambió. Actualiza la página.");r.data.owner=z.string().trim().min(1).max(180).parse(data.owner);r.data.startDate=dateSchema.parse(data.startDate);r.data.checks=z.object({scope:z.boolean(),quotes:z.boolean(),permits:z.boolean(),crew:z.boolean()}).parse(data.checks);r.data.status=z.enum(["scheduled","active","blocked","complete"]).parse(data.status);if(r.data.status==="active"){const errors=activationErrors(r,records);if(errors.length)throw new Error(errors.join(" · "));}if(r.data.status==="complete"&&!data.closeoutRef?.trim())throw new Error("Registra evidencia de entrega/aceptación del cierre.");if(data.closeoutRef)r.data.closeoutRef=z.string().max(500).parse(data.closeoutRef);ref=r.id;statements.push(updateRecord(r,r.version));
 }else if(b.action==="ledger"){
 const c=ledgerSchema.parse(data);await lookup(c.projectId,"project");if(!c.reference.trim())throw new Error("Registra la referencia de factura, recibo o comprobante.");if(c.type==="payment")c.paid=true;if(records.some(r=>r.kind==="ledger"&&r.data.type===c.type&&r.data.projectId===c.projectId&&r.data.reference===c.reference))throw new Error("Esa referencia ya está registrada para esta obra.");const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify([demo,c.projectId,c.type,c.reference])));const id="ledger-"+Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,"0")).join("");const r=fresh("ledger",c,demo,id);ref=r.id;statements.push(insertRecord(r));
 }else if(b.action==="expense-paid"){
 const r=await lookup(data.id,"ledger");if(r.data.type!=="expense")throw new Error("El registro debe ser un gasto.");r.data.paid=true;ref=r.id;statements.push(updateRecord(r,r.version));
 }else if(b.action==="task"){
 const c=taskSchema.parse(data);if(c.projectId)await lookup(c.projectId,"project");if(c.contactId)await lookup(c.contactId,"contact");const r=fresh("task",{...c,done:false},demo);ref=r.id;statements.push(insertRecord(r));
 }else if(b.action==="task-toggle"){
 const r=await lookup(data.id,"task");r.data.done=z.boolean().parse(data.done);ref=r.id;statements.push(updateRecord(r,r.version));
 }else if(b.action==="change"){
 const c=changeSchema.parse(data);await lookup(c.projectId,"project");const r=fresh("change",{...c,acceptedAt:new Date().toISOString()},demo);ref=r.id;statements.push(insertRecord(r));
 }else if(b.action==="import-contacts"){
 const list=z.array(z.any()).min(1).max(25).parse(data.contacts),seen=new Set(records.filter(r=>r.kind==="contact").flatMap(r=>contactKeys(r.data)).filter(Boolean));let count=0;for(const item of list){const c=contactSchema.parse(item);if(c.stage==="won")throw new Error("Importa oportunidades sin ganar; la aceptación requiere una cotización.");const key=contactKey(c);if(contactKeys(c).some(k=>seen.has(k)))continue;for(const k of contactKeys(c))seen.add(k);const r=fresh("contact",c,demo);statements.push(insertRecord(r),insertRecord(fresh("task",{title:`Calificar a ${c.name}`,owner:c.owner,due:c.nextDue,contactId:r.id,projectId:"",notes:"Verificar datos antes de contactar.",done:false},demo)));count++;}notice=`${count} contactos importados. Duplicados omitidos.`;if(!count)return json({ok:true,notice});
 }else if(b.action==="demo"){
 if(!demo)throw new Error("El recorrido usa exclusivamente datos de ejemplo.");if(records.length)return json({ok:true,notice:"El recorrido ya está cargado."});const c=fresh("contact",{name:"Cliente de ejemplo",company:"DFW Property · Ejemplo",email:"example@example.com",phone:"",city:"Dallas",service:"Concreto",source:"Referido",owner:"Mich",nextDue:addDays(1),valueCents:900000,stage:"won",consent:false,notes:"Datos simulados para aprender el flujo."},true,"demo-contact"),em=estimateMath({items:[{quantity:1,unitCostCents:400000}],overheadPct:10,contingencyPct:5,marginPct:25}),e=fresh("estimate",{contactId:c.id,title:"Patio de concreto · Ejemplo",scope:"Placa de ejemplo. Medidas y diseño por confirmar en una obra real.",exclusions:"Permisos y trabajos adicionales sujetos a revisión.",items:[{description:"Materiales y mano de obra · Ejemplo",quantity:1,unit:"lote",unitCostCents:400000}],overheadPct:10,contingencyPct:5,marginPct:25,depositPct:30,owner:"Mich",validUntil:addDays(14),...em,status:"accepted",signedRef:"EJEMPLO",acceptedBy:"Cliente de ejemplo"},true,"demo-estimate"),p=fresh("project",{estimateId:e.id,contactId:c.id,title:e.data.title,scope:e.data.scope,...em,depositPct:30,owner:"Mich",status:"active",startDate:addDays(-1),checks:{scope:true,quotes:true,permits:true,crew:true}},true,"demo-project");for(const r of[c,e,p,fresh("ledger",{projectId:p.id,type:"payment",description:"Anticipo · Ejemplo",amountCents:Math.round(em.priceCents*.3),date:addDays(-2),paid:true,reference:"DEMO-001"},true),fresh("ledger",{projectId:p.id,type:"expense",description:"Materiales · Ejemplo",amountCents:140000,date:addDays(-1),paid:true,reference:"DEMO-002"},true),fresh("task",{title:"Confirmar entrega de materiales · Ejemplo",owner:"Mich",due:addDays(0),contactId:c.id,projectId:p.id,notes:"Tarea simulada.",done:false},true)])statements.push(insertRecord(r));notice="Recorrido de ejemplo listo.";
 }else throw new Error("Acción no válida.");
 await commit(statements,requestId,b.action,request.headers.get("oai-authenticated-user-email")||"Propietario",demo,ref);return json({ok:true,id:ref,notice});
 }catch(e:any){const message=e instanceof z.ZodError?e.issues.map((x:any)=>`${x.path.join(".")}: ${x.message}`).join(" · "):e.message;if(/UNIQUE constraint/.test(message))return json({error:"Ya existe un registro equivalente. Actualiza la página."},409);return json({error:message||"No se pudo guardar. Conserva los datos e intenta nuevamente."},400);}}
