import{saveConnection,testConnection,searchApollo,pullGHL,pushGHL,ollamaDraft}from"@/lib/ops-integrations";import{getRecord,db,connectionSummary}from"@/lib/ops-db";import{z}from"zod";
export const dynamic="force-dynamic";
export async function POST(request:Request){try{const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Error("Origen no permitido.");const b:any=await request.json();if(b.demo===true)throw new Error("Cambia a Mi compañía para usar conexiones reales.");const provider=z.enum(["apollo","gohighlevel","ollama"]).parse(b.provider);
 if(b.action==="save"){await saveConnection(provider,b.data);return Response.json({ok:true,notice:"Credencial guardada. Verifica la conexión.",connections:await connectionSummary()});}
 if(b.action==="test")return Response.json({ok:true,...await testConnection(provider),connections:await connectionSummary()});
 if(b.action==="remove"){await db().prepare("DELETE FROM credentials WHERE provider=?").bind(provider).run();return Response.json({ok:true,connections:await connectionSummary()});}
 if(b.action==="apollo-search"&&provider==="apollo"){const titles=z.array(z.string().min(1).max(100)).min(1).max(10).parse(b.data.titles),location=z.string().min(1).max(100).parse(b.data.location),page=z.number().int().min(1).max(500).parse(b.data.page||1);return Response.json({ok:true,...await searchApollo(titles,location,page)});}
 if(b.action==="ghl-pull"&&provider==="gohighlevel"){const page=z.number().int().min(1).max(1000).parse(b.data?.page||1);return Response.json({ok:true,...await pullGHL(page),page});}
 if(b.action==="ghl-push"&&provider==="gohighlevel"){const r=await getRecord(z.string().parse(b.data.id),false);if(r.kind!=="contact")throw new Error("Selecciona un contacto.");const result=await pushGHL(r.data);return Response.json({ok:true,contactId:result.contact?.id,notice:"Contacto sincronizado con GoHighLevel."});}
 if(b.action==="draft"&&provider==="ollama"){const r=await getRecord(z.string().parse(b.data.id),false);if(r.kind!=="contact")throw new Error("Selecciona un contacto.");const context={name:r.data.name,company:r.data.company,city:r.data.city,service:r.data.service,stage:r.data.stage,notes:r.data.notes};return Response.json({ok:true,draft:await ollamaDraft("Redacta un seguimiento para revisión. Datos del contacto:\n"+JSON.stringify(context))});}throw new Error("Acción no válida.");
 }catch(e:any){return Response.json({error:e instanceof z.ZodError?"Revisa los datos de conexión.":e.message},{status:400,headers:{"Cache-Control":"no-store"}});}}
